
services:
    app:
      image: fizzbuzz2/cancelation:v1.0.0
      build:
        platforms:
          - linux/amd64
          - linux/arm64
        context: . # docker-compose.yml in current directory
